### ISSUE TITLE
Live tail plugin logs

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#660] opened 2020-10-08 17:49 UTC
In V3 we added the ability to grab the log files of a plugin. We should add another feature to poll for those log files that way a user can monitor the plugin logs in a "live" format.

**Comment by hazmat345** [comment] 2020-10-09 15:04
Think this is a duplicate of #39

**Comment by TheBurchLog** [comment] 2020-10-15 12:05
@hazmat345 
I think this are two different scopes. #39 wants to see the live logs of a specific request, where this one is seeing the live logs of the entire plugin. I don't know how we would pull just the logs of an ongoing request as it hops around between systems/commands.

**Closed** 2022-05-25 16:25 UTC
Labels: brewtils, feature, user request, future
