### ISSUE TITLE
Confirm RPM scripts work

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#143] opened 2018-08-15 19:47 UTC
The following need to work before we close the door on 2.4.0.

# CentOS 6
* [x] - Fresh Install
Hazmat edit:
* [ ] - ~Update from 2.3.X~
* [ ] - ~Update from 2.1.X~
* [ ] - ~Erase RPM~
* [ ] - ~Verify `/var/run/beer-garden/` bug~
* [ ] - ~Install, erase, Install~
* [ ] - ~Labeling Configuration files correctly~

# CentOS 7
* [x] - Fresh Install
* [x] - Update from 2.3.X
* [x] - Update from 2.1.X
* [x] - Erase RPM
* [x] - Verify `/var/run/beer-garden/` bug
* [x] - Install, erase, Install
* [x] - Labeling Configuration files correctly

**Comment by hazmat345** [comment] 2018-08-20 23:45
I don't think 2.2.X ever existed - I believe we skipped 2.2 in order to re-sync with brewtils versions. I'm assuming that means we want to support upgrading from 2.1.X instead?

**Comment by hazmat345** [comment] 2018-08-24 19:13
I wrote this on a post-it note, it should probably be somewhere more permanent (like here):

> Local install needs UI to be built

**Comment by hazmat345** [comment] 2018-08-31 23:02
@loganasherjones what does this mean?

> Labeling Configuration files correctly

**Comment by loganasherjones** [comment] 2018-08-31 23:30
This means that if we create a `yaml` file we should label it with `.yaml` and same thing for a `json` file.

**Comment by hazmat345** [comment] 2018-09-03 00:34
When the rpm is erase it leaves behind plugins, logs, and configuration files. That's intended behavior, right?

**Comment by loganasherjones** [comment] 2018-09-03 00:36
That is the correct behavior yes.

**Comment by hazmat345** [comment] 2018-09-03 00:51
For the labeling, I'm pretty sure this works? We'll generate yaml files by default for the clean install case. For the upgrade case if either json or yaml files exist we'll upgrade them in-place and they'll remain whatever they were.

If you manually use the `generage_bartender_config` entry point you can specify `--configuration-file` and `--configuration-type`. `type` defaults to yaml, but if you specify a file and the file ends in ".json" we'll assume you want json and do that for you. If you specify a file and and type but the file doesn't have an extension we will not append the extension.

**Comment by hazmat345** [comment] 2018-09-09 15:17
Closing this out

**Closed by hazmat345** 2018-09-09 15:17 UTC
