### ISSUE TITLE
Health and status monitor endpoint for external system

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#133] opened 2018-08-03 18:14 UTC
From beer-garden/brew-view#19:

It would be really cool if you could specify some sort of status endpoint for an external system. We could use that for determining if the external system is up before making a request.

**Comment by TheBurchLog** [comment] 2024-05-02 13:34
Duplicate of https://github.com/beer-garden/beer-garden/issues/150

**Closed by TheBurchLog** 2024-05-02 13:34 UTC
Labels: feature
