### ISSUE TITLE
Shutdown error after creating request to child

### ISSUE THREAD

**Issue by west270** [beer-garden/beer-garden#753] opened 2020-11-19 16:43 UTC
When I made a request to child then shutdown the parent I would receive an error during shutdown. 
Clearing queue in `QueueListener` during stop function resolves issue

Error: 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/bjwest3/Documents/beer-garden/src/app/beer_garden/events/processors.py", line 51, in run
    self.process(self._queue.get(timeout=0.1))
  File "/usr/lib64/python3.7/multiprocessing/queues.py", line 108, in get
    res = self._recv_bytes()
  File "/usr/lib64/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib64/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib64/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by hazmat345** [comment] 2021-06-11 20:01
I'm not able to reproduce this - there's been a lot of changes since this was opened that should have improved this. Going to go ahead and close this as OBE, please reopen if it's still an issue.

**Closed by hazmat345** 2021-06-11 20:01 UTC
