### ISSUE TITLE
Incorrect URL mapping for commands list

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#851] opened 2021-01-29 18:05 UTC
The displayed commands are not correct if the `namespace` field is not present in the URL. Things work correctly with this URL:

> /#!/commands?namespace=default&systemName=echo&systemVersion=3.0.0.dev0

But removing the namespace query parameter results in ALL commands being displayed:

> /#!/commands?systemName=echo&systemVersion=3.0.0.dev0

Interestingly, it seems like removing either of the other parameters works as expected.

**Comment by hazmat345** [comment] 2021-07-13 16:31
This is a purely angular frontend bug but I'm leaving it open as it was noticed by a user.

**Comment by scott-taubman** [comment] 2022-05-25 16:22
I may be missing it, but I wouldn't expect either of those URLs to do anything based on the routes that exist in current beer-garden, and also it's not obvious to me how someone would get directly to the commands page to begin with.  I'm going to close this one and we can reopen it if someone can articulate what the issue is we're trying to fix.

**Closed by scott-taubman** 2022-05-25 16:22 UTC
Labels: bug, ui, user request
