### ISSUE TITLE
Do not process events for Requests in a terminal state

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/beer-garden#1214] opened 2021-12-07 18:43 UTC
The way remote garden connections get configured is highly confusing and can easily lead to situations where events actually get double published.  There are probably other paths that result in events either being received multiple times or received out of order.  One of the impacts of this is that a garden will often receive an event for a Request that has already reached a terminal state.  The backend does not allow for the status of such a Request to be updated, but the event handler will try anyway, resulting in a message showing up in the log stating that the request could not be updated.

This message isn't particularly useful and in certain circumstances, the volume of such messages can really clutter the logs.  What would probably be preferable is to just check if the request is in a terminal state before attempting to process the event for it, and if it is just treat the event as a no-op and log nothing.  Or slightly better, just log a "DEBUG" message indicating that an event was received for a Request in a terminal state, but don't attempt to process the event.

If making the determination about whether the event should be processed or not is non-trivial, another approach could be to just let the event be processed, but catch the exception that is raised when attempting to update a request in a terminal state (if it is not already a specific exception being thrown, make it one) and then log the DEBUG message from that.

**Comment by scott-taubman** [comment] 2021-12-20 14:19
> ...another approach could be to just let the event be processed, but catch the exception that is raised when attempting to update a request in a terminal state (if it is not already a specific exception being thrown, make it one) and then log the DEBUG message from that.

I started looking to this issue briefly just to add some more details to the issue and at first blush it looks like the code attempts to behave exactly as I've suggested it should.  See [here](https://github.com/beer-garden/beer-garden/blob/3.9.0/src/app/beer_garden/db/mongo/models.py#L498) where it raises an exception for an invalid state transition and [here](https://github.com/beer-garden/beer-garden/blob/3.9.0/src/app/beer_garden/requests.py#L900) where it catches said exception and just keeps rolling on.  The message still end up being output to the logs as an error, though it's not clear why looking at those two references lines.  I'll leave solving that mystery as an exercise for whoever takes this issue.

**Comment by west270** [comment] 2021-12-22 19:16
This problem is caused by having multiple forwarding paths configured to forward to a parent. Since there is no good way to fix this issue at the moment, I am closing the issue.

**Comment by scott-taubman** [comment] 2022-01-18 21:18
I'm going to re-open this based on a re-investigation of this issue.  It turns out that the issue described here is actually handled somewhat gracefully within the existing code.  The real problem is that there is duplicate processing happening on every request, even without duplicate events getting published.  Duplicate events combined with the duplicate processing taking place will result in a bunch of noisy error messages, but the underlying issue is the processing.

The gist of the problem is that the entrypoint processes (HTTP and STOMP) and the main process all call [`requests.handle_event`](https://github.com/beer-garden/beer-garden/blob/3.10.0/src/app/beer_garden/requests.py#L863) as part of their processing pipeline.  The problem with that being that all 3 end up going through the effort of updating the request.  Really we only ever need one of them to do the update.

What I believe can be done is we can split that `handle_event` into two separate functions that can get called in the different contexts.  The entrypoints really just care about the first half of that function, so the other half (the part that actually updates the database) can be its own thing that only gets called by the main process.

**Closed** 2022-01-19 20:38 UTC
