### ISSUE TITLE
System Admin Page Redesign

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#778] opened 2020-12-03 14:10 UTC
The System Admin page is becoming very unbalanced when a plugin has multiple deployments across various namespaces and instances. We need to address a better way to visually display this data. 

The big things to consider:
* Grouping of like Systems either by Namespace or System Name
* Functions that target the Namespace-System-Version and the Instance
* How to give admins a quick view of everything online vs offline

**Comment by hazmat345** [comment] 2020-12-04 17:26
This looks like a duplicate #603

**Comment by hazmat345** [comment] 2021-07-13 16:16
Closing as a duplicate of #603.

**Closed by hazmat345** 2021-07-13 16:16 UTC
Labels: duplicate
